jobs:
- job: CPU
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: |
     docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
     cd dockerfiles
     make docker_build_cpu
     ./push.sh docker_push_cpu
- job: GPU
  timeoutInMinutes: 0
  pool: 'Ubuntu 16.04'
  steps:
  - bash: |
     docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
     cd dockerfiles
     make docker_build_gpu
     ./push.sh docker_push_gpu
#- job: Update_Microbadger
#  dependsOn:
#  - CPU
#  - GPU
#  steps:
#  - script: 'curl -X POST https://hooks.microbadger.com/images/carml/go-pytorch/LhaNimlmXzse3g4UF1HZ1LfchSo='
# variables:
# - group: Docker Auth
